name: Generate ISO codelist catalogue from codelist CSV tables âš™ï¸

on:
  push:
    branches:
      - master
    paths:
      - 'dist/WMOCodeLists.xml'
  pull_request:
    branches:
      - master

jobs:
  autogenerate_wmo_codelist_catalogue_xml:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository â˜‘ï¸
      uses: actions/checkout@v2
    - name: Install requirements ðŸ“¦
      run: |
        python3 -m pip install --upgrade pip
        pip3 install jinja2
    - name: setup git config ðŸ“¦
      run: |
        git config --global user.email "tomkralidis@gmail.com"
        git config --global user.name "Tom Kralidis"
    - name: generate codelist catalogue âš™ï¸
      run: | 
        python3 scripts/generate-codelist-catalogue.py > dist/WMOCodeLists.xml
        git commit -am "update ISO codelist catalogue"
        git push origin ${{ github.ref }}
