name: Generate ISO codelist catalogue from codelist CSV tables âš™ï¸

on: [ push, pull_request ]

jobs:
  autogenerate_wmo_codelist_catalogue_xml:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Set up Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements ðŸ“¦
      run: |
        python3 -m pip install --upgrade pip
        pip3 install jinja2
    - name: generate codelist catalogue âš™ï¸
      run: | 
        python3 scripts/generate-codelist-catalogue.py > dist/WMOCodeLists.xml
        git config --global user.email "efucile@wmo.int"
        git config --global user.name "Enrico Fucile"
        git add .
        git commit -m "update ISO codelist catalogue" dist/WMOCodeLists.xml
        git push
